name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download main file
        uses: actions/download-artifact@v2.1.1
        with:
          name: file

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v2.5.0

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: marcusviniciusdev/go_cicd:${{github.ref_name}}
